-- Active: 1707017149560@@191.101.79.205@3306@u258074489_AERSDATA

-- create the table
CREATE TABLE PULLER_RECORDS(
    ID VARCHAR(255),
    AERSID INT,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    ELO FLOAT,
    LASTMATCH VARCHAR(50),
    ARM VARCHAR(50),
    WEIGHT VARCHAR(50),
    DIVISION VARCHAR(50),
    LEAGUE VARCHAR(50),
    PRIMARY KEY (ID)
);


SELECT * FROM PULLER_RECORDS

-- if the AUTO_INCREMENT is not correct, you can manually set the current number
-- ALTER TABLE PULLER_RECORDS AUTO_INCREMENT = 1;
DROP TABLE `PULLER_RECORDS`

-- This command will clear all non-test data since our test record is id = 1
DELETE FROM `PULLER_RECORDS` WHERE ID <> 1